{"cells":[{"kind":2,"language":"lox","value":"fun returnSum(a: number, b: number): number {\n    print (\"returnSum\");\n    return a + b;\n}\n\n// Closures\n\nfun identity(a: (number, number) => number): (number, number) => number {\n    print (\"identity\");\n    return a;\n}\n\n// Calls identity with reference to function as argument, which is returned,\n// and apply (1, 2) on that function, which\n// Obviously identity is called before returnSum.\nprint identity(returnSum)(1, 2); \n\n// Calls returnSum, then identity is called with that return value as argument.\n// Obviously returnSum is called before identity.\n// print identity(returnSum(1, 2)); \n// But: This should fail, as the number return value is no valid argument for a: (number, number) => number    !!!\n\n\n// var av = 1;\n// av();\n// Expected: Cannot call a non-function\n"},{"kind":2,"language":"lox","value":"fun aFunction(aLambda: (number) => number, aNumber: number): number {\n    return aLambda(aNumber);\n}\n\nfun aTimesTwo(a: number): number {\n    return a * 2;\n}\n\nvar result = aFunction(aTimesTwo, 9);\nprint result;"}]}